

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=admin
      - DB_PASS=secret
      - PORT=5000
    volumes:
      - .:/app
    command: npm start

volumes:
  postgres_data:
